version: '3.1'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# docker stack deploy -c docker-compose.yml docker-compose_mysql
